# Generated by Django 5.1.8 on 2025-04-18 18:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(help_text='Unique room number within the hotel.', max_length=10, verbose_name='Room Number')),
                ('type', models.CharField(choices=[('Sgl', 'Single'), ('Dbl', 'Double'), ('Twn', 'Twin'), ('Ste', 'Suite')], default='SGL', max_length=3, verbose_name='Room Type')),
                ('price', models.DecimalField(decimal_places=2, help_text="Price per night in the hotel's currency.", max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('is_available', models.BooleanField(default=True, help_text='Indicates whether the room is available for booking.', verbose_name='Is Available')),
                ('description', models.TextField(blank=True, help_text='Optional description of the room.', null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.hotel', verbose_name='Hotel')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['hotel', 'room_number'],
                'unique_together': {('hotel', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='RoomPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='room_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='rooms.room')),
            ],
        ),
    ]
