# Generated by Django 5.1.8 on 2025-04-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='test',
            field=models.CharField(blank=True, help_text='This is a test field.', max_length=100, null=True, verbose_name='Test Field'),
        ),
    ]
