# Generated by Django 5.1.8 on 2025-04-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text="Price per night in the hotel's currency.", max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('SGL', 'Single'), ('DBL', 'Double'), ('TWN', 'Twin'), ('STE', 'Suite')], default='SGL', max_length=3, verbose_name='Room Type'),
        ),
    ]
