# Generated by Django 5.1.8 on 2025-04-15 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='test',
        ),
    ]
