version: "3.8"

services:
  db:
    image: postgres:17-alpine
    container_name: hotelhub_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - app_net
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: "redis:8.0-rc1-bookworm"
    networks:
      - app_net

  web:
    build: .
    command: ["daphne", "-b", "0.0.0.0", "-p", "8000", "hotelhub.asgi:application"]
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app_net
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      REDIS_URL: redis://redis:6379/1  

  celery_worker:
    build: .
    command: ["celery", "-A", "hotelhub", "worker", "-l", "debug"]
    depends_on:
      - redis
    networks:
      - app_net
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0

  celery-beat:
    build: .
    command: celery -A hotelhub beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - redis
      - web

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9201:9200"
      - "9300:9300"
    networks:
      - app_net
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5602:5601"
    depends_on:
      - elasticsearch
    networks:
      - app_net

networks:
  app_net:

volumes:
  postgres_data:
  elasticsearch_data: