# Generated by Django 5.1.8 on 2025-04-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='breakfast_price',
            field=models.IntegerField(default=0, help_text='Price of breakfast per person'),
        ),
    ]
