# Generated by Django 5.1.8 on 2025-04-16 17:55

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country',
            field=django_countries.fields.CountryField(default='Azerbaijan', max_length=2),
        ),
    ]
