# Generated by Django 5.1.8 on 2025-04-14 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_delete_customeruser'),
        ('hotels', '0002_alter_hotel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Owner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels', to='accounts.customuser'),
        ),
    ]
