# Generated by Django 5.2 on 2025-04-11 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_alter_hotel_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='country',
        ),
    ]
