# Generated by Django 5.1.8 on 2025-04-20 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='wishlist',
        ),
    ]
