# Generated by Django 5.1.8 on 2025-04-12 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
