# Generated by Django 5.1.8 on 2025-04-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_wishlist'),
        ('hotels', '0002_hotel_breakfast_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlisted_by', to='hotels.hotel'),
        ),
    ]
